# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 787940487d7e9d2d447229e924d46eb5cb70d5d159e25a38afffdb9ad4acbe0b6e2c376c37dc72c47b5852bae633b6f40c23e8b95f24f67bd5acd0cded03d6fa

test:
  secret_key_base: ef45ead9e868e4b63d7ae15cf3decd71d76313331d0e1a9325030c8dc4ad7253f498cf349593b5b7b8d3d347d3d4636172ca30ce2e309ece1d51ec3f8da93699

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
